# Generated by Django 5.2.17 on 2026-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_city_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='address',
            field=models.TextField(default='Near Mahavir Chowk Ganguli, Benipatti'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='alt_phone',
            field=models.CharField(default='+91 72950 77559', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='phone',
            field=models.CharField(default='7295077559', max_length=20),
        ),
    ]
