# Generated by Django 5.2.17 on 2026-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_gateway_order_id_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='upi_id',
            field=models.CharField(default='7050830610@ptsbi', max_length=100),
        ),
    ]
