# Generated by Django 5.2.17 on 2026-09-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storesetting_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='free_delivery_above',
            field=models.DecimalField(decimal_places=2, default=249.0, max_digits=8),
        ),
    ]
