# Generated by Django 5.2.17 on 2026-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='Bihar', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='Bihar', max_length=100),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
    ]
